#!/bin/bash
echo 'To test LTE connectivity, follow these instructions.'
echo '* insert a M2M SIM card into SIM1 slot'
echo '* ensure you know the address of your APN'
echo '* open minicom on serial port /dev/ttyUSB2 (minicom -d /dev/ttyUSB2)'
echo '* enter the following commands:'
echo '  AT+CGDCONT=1,"IP","<yourAPNaddress>"'
echo '  AT!SCACT=1,1'
echo '* close minicom'
echo '* check the following:'
echo '  one of the eth interfaces from GobiNet driver has a valid configuration'
echo '  (ip address, netmask...)'
echo '  you can ping domain names: ping www.google.com '
echo '  you can download web pages: wget http://www.google.com '