KERNEL_SRC = /lib/modules/`uname -r`/build

all: build

obj-m += xr17v35x.o

xrpci-objs :=	xr17v35x.o

EXTRA_CFLAGS += -DDEBUG=1

build:
	$(MAKE) -C $(KERNEL_SRC) SUBDIRS=$(PWD) modules

install:
	cp xr17v35x.ko /lib/modules/$(shell uname -r)/kernel/drivers/char
	depmod -a

clean:
	rm -f *~ *.o
	rm -f *~ *.ko
	rm -f modules.order Module.symvers xr17v35x.mod.c
